package com.j256.simplemagic.logger;

/**
 * "Fluent" logger which uses method chaining to support the logging calls. This causes no additional objects to be
 * generated if the logging level is not enabled -- even when logging primitives. You get a fluent-logger by calling
 * {@link LoggerFactory#getFluentLogger(String)}.
 *
 * For example, even with the port argument being an int primitive below, there are no objects generated by this call
 * unless TRACE log level is enabled. If TRACE is enabled then there is an additional @{link {@link FluentContext}
 * object which holds the message, throwable, and arguments array is allocated.
 *
 * <pre>
 * fluentLogger.atLevel(Level.TRACE) <!-- -->
 *   .msg("connected to host '{}' port '{}'") <!-- -->
 *   .arg(host) <!-- -->
 *   .arg(port) <!-- -->
 *   .log();
 * </pre>
 *
 * From SimpleLogging: https://github.com/j256/simplelogging
 *
 * @author graywatson
 */
public class FluentLogger extends BaseLogger {

    public FluentLogger(LogBackend backend) {
        super(backend);
    }

    /**
     * Start of the chaining that sets the log level of the message. If this level is not enabled then the method
     * returns a mute context singleton and all calls to it are no-ops.
     */
    public FluentContext atLevel(Level level) {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Start of the chaining that sets the log level of the message at a TRACE level. If TRACE not enabled then the
     * method returns a mute context singleton and all calls to it are no-ops.
     */
    public FluentContext atTrace() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Start of the chaining that sets the log level of the message at a DEBUG level. If DEBUG not enabled then the
     * method returns a mute context singleton and all calls to it are no-ops.
     */
    public FluentContext atDebug() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Start of the chaining that sets the log level of the message at an INFO level. If INFO not enabled then the
     * method returns a mute context singleton and all calls to it are no-ops.
     */
    public FluentContext atInfo() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Start of the chaining that sets the log level of the message at a WARNING level. If WARNING not enabled then the
     * method returns a mute context singleton and all calls to it are no-ops.
     */
    public FluentContext atWarn() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Start of the chaining that sets the log level of the message at an ERROR level. If ERROR not enabled then the
     * method returns a mute context singleton and all calls to it are no-ops.
     */
    public FluentContext atError() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Start of the chaining that sets the log level of the message at a FATAL level. If FATAL not enabled then the
     * method returns a mute context singleton and all calls to it are no-ops.
     */
    public FluentContext atFatal() {
        throw new UnsupportedOperationException("STUB: not implemented");
    }

    /**
     * Context that doesn't do anything. This is returned when the log level is not enabled.
     */
    private static class MuteContext implements FluentContext {

        /**
         * singleton instance of the context that is used by all calls when level not enabled
         */
        public static final MuteContext SINGLETON = new MuteContext();

        @Override
        public FluentContext msg(String message) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext appendMsg(String message) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext throwable(Throwable th) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(Object arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(boolean arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(byte arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(char arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(short arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(int arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(long arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(float arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext arg(double arg) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public FluentContext args(Object[] args) {
            throw new UnsupportedOperationException("STUB: not implemented");
        }

        @Override
        public void log() {
            throw new UnsupportedOperationException("STUB: not implemented");
        }
    }
}
